import re

with open('/Users/sull/Documents/untitled folder/Vehicle_AtoB/scripts/heuristic.py', 'r') as f:
    content = f.read()

# The issue is that the vehicle is stuck because the forward path is blocked by an obstacle!
# nx=13, ny=28 has h=inf.
# Why is it blocked? Because it's too close to an obstacle.
# But wait, if h=19.28 at nx=15, ny=29, it means there IS a path from nx=15, ny=29 to the goal!
# How did Dijkstra find a path to nx=15, ny=29?
# It must have come from some neighbor!
# If it came from a neighbor, then that neighbor must have a lower h value!
# But all neighbors have either h=inf or h > 19.28!
# Wait, how can a neighbor have h > 19.28 if it was the parent?
# In Dijkstra, h(A) = h(B) + cost(A->B).
# So h(B) = h(A) - cost(A->B) < h(A).
# So there MUST be a neighbor B with h(B) < h(A).
# Let's check the neighbors again.
# The neighbors of A are generated by:
# B = A - d_step * cos(th_A)
# This is EXACTLY what I did in test_3d_path_fix8.py!
# d_step=0.5, steer=0.0: nx=17, ny=30, nth=1, dir=1, h=24.03
# d_step=-0.5, steer=0.0: nx=13, ny=28, nth=1, dir=0, h=inf
# So the neighbors are nx=17 and nx=13.
# But neither of them has h < 19.28!
# How is this possible?
# Because Dijkstra uses d_step = 0.5, but it ALSO uses d_step = -0.5!
# If Dijkstra expanded from B to A, then:
# h(A) = h(B) + cost.
# So h(B) = h(A) - cost.
# This means B must be one of the neighbors generated by the Dijkstra expansion!
# Let's write a script to find EXACTLY which neighbor generated A in Dijkstra.
